global:
  scrape_interval: 15s
  evaluation_interval: 15s
  
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'flask'
    scrape_interval: 10s
    static_configs:
      - targets:
        - '172.18.0.20:5000'
        - '172.18.0.21:5000'
        - '172.18.0.22:5000'
        - '172.18.0.23:5000'