global:
  scrape_interval: 15s
  evaluation_interval: 15s
  
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'flask'
    scrape_interval: 10s
    static_configs:
      - targets:
        - '172.17.0.3:5000'
        # - '172.17.0.4:5000'
        # - '172.17.0.5:5000'
        # - '172.17.0.6:5000'